### PR TITLE
feat: add cmd+l and ctrl+l keyboard shortcut

### PR DESCRIPTION
**Pull request by treemmett**

### CODE REVIEW

**Comment by undesicimo** [comment]
praise: wanted this really bad. Hope this gets implemented

**Comment by Bin-Huang** [comment]
I really like this PR, it's amazing! 😍😍 I can't believe I didn't think of doing this earlier. I do have a small question though - I noticed that the shortcut key in actual use is Ctrl+L, and it seems to be the same in the code. I'm just a bit confused as to why Ctrl+L was chosen as the shortcut key. Could you please help me understand the reasoning behind this?

**Comment by treemmett** [comment]
> I really like this PR, it's amazing! 😍😍 I can't believe I didn't think of doing this earlier. I do have a small question though - I noticed that the shortcut key in actual use is Ctrl+L, and it seems to be the same in the code. I'm just a bit confused as to why Ctrl+L was chosen as the shortcut key. Could you please help me understand the reasoning behind this?

[I've copied the "Jump to address bar" shortcut from Chromium.](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Caddress-bar-shortcuts) Chrome uses ctrl as the modifier key on Windows, and cmd as the modifier on Mac. I've included both versions to remain intuitive to users across platforms.

**Comment by Bin-Huang** [comment]
Thank you for your quick response. I was wondering why the "L" key was chosen, but now I think I have an answer. In Chrome's "Jump to address bar" shortcut, "L" is easily associated with the word "Link" and the address bar, which makes it easy to remember. Regarding Chatbox, I think selecting "I" for the input box might be more suitable, as it would be easily associated with the word "Input" and the message input box. Of course, this is just my personal opinion, and I would love to hear any other suggestions you may have.

**Pull request merged**
