### PR TITLE
dazugpt_prompt

### PR DESCRIPTION
**Pull request by AiDriveOne**
prompt

### CODE REVIEW

**Review by backbenchers10 — COMMENTED** [review]
Hello

**Comment by AiDriveOne** [comment]
@AiDriveOne
[dazugpt_prompt.py](https://github.com/Bin-Huang/chatbox/pull/634/commits/9cea5a78584b2cc6a299f4e317d0a3f64cdc763d) 
[9cea5a7](https://github.com/Bin-Huang/chatbox/pull/634/commits/9cea5a78584b2cc6a299f4e317d0a3f64cdc763d)
@AiDriveOne
[Update dazugpt_prompt.py](https://github.com/Bin-Huang/chatbox/pull/634/commits/13cb59340d0ad12a50d25c42c7ce3245e65f4510) 
[13cb593](https://github.com/Bin-Huang/chatbox/pull/634/commits/13cb59340d0ad12a50d25c42c7ce3245e65f4510)
@AiDriveOne
[Rename dazugpt_prompt.py to dazugpt_prompt](https://github.com/Bin-Huang/chatbox/pull/634/commits/bca762b60820d1adbeba2b2ecc15812e15e55a16) 
[bca762b](https://github.com/Bin-Huang/chatbox/pull/634/commits/bca762b60820d1adbeba2b2ecc15812e15e55a16)
@AiDriveOne
[dazu_image_classifier_py.](https://github.com/Bin-Huang/chatbox/pull/634/commits/0a58a10f8efb6f1630da9932c58bedcde29d0a42) 
[0a58a10](https://github.com/Bin-Huang/chatbox/pull/634/commits/0a58a10f8efb6f1630da9932c58bedcde29d0a42)
@AiDriveOne
[Merge branch 'Bin-Huang:main' into main](https://github.com/Bin-Huang/chatbox/pull/634/commits/749a813549c35f3361359ad7e70584e90126003e)

**Comment by Bin-Huang** [comment]
Hello, thank you very much for your contribution. How can I use these prompts in a chatbox? Is it still work-in-progress?

**Comment by AiDriveOne** [comment]
Cool

**Comment by AiDriveOne** [comment]
Ok

**Review by AiDriveOne — COMMENTED** [review]
It's looks great)

dazu_image_classifier_py.

**Comment by Bin-Huang** [comment]
I'm sorry but I don't think we can merge this PR into the application. Nonetheless, thank you for your contribution and enthusiasm.

**Pull request closed without merging**
