### PR TITLE
(Feature) Allow Selecting OpenAI Model, Context Size, & Reply Size in Settings

### PR DESCRIPTION
**Pull request by joegoldin**
This PR allows users to:
- configure which chat completion model is used
	- applied when a new session is created
	- `gpt-3.5-turbo` (default)
	- `gpt-3.5-turbo-0301`
	- `gpt-4` (must have API access, currently limited)
	- `gpt-4-0314` (must have API access, currently limited)
	- `gpt-4-32k` (must have API access, currently limited and they are processing applications separately from the normal gpt4 model)
	- `gpt-4-32k-0314` (must have API access, currently limited and they are processing applications separately from the normal gpt4 model)
- set max context size
	- now calculated in tokens
	- defaults to `inf` (do we want this to default to `4096`, the max context size for gpt-3.5 @Bin-Huang?
- set max tokens per reply
	- defaults to `2048`
- toggle displaying model name with other tips (token/word count)

image
image

### CODE REVIEW

**Comment by joegoldin** [comment]
@Bin-Huang I'll hold off on any more features until the Tauri re-write -- excited for that!

**Comment by Bin-Huang** [comment]
Haha, no need to worry, I am waiting for you to complete this PR. Is it now available for review and merge, or are you still working on it?

@joegoldin

**Comment by Bin-Huang** [comment]
I'm just waiting for your PR to be merged. As soon as it's merged, I'll start refactoring with Tauri. I have been playing with Tauri for a day now, and like you, I also feel excited about it. 😁😁😁😁😁

**Comment by joegoldin** [comment]
@Bin-Huang Yep! It's ready for your review and merge :) sorry, didn't see this comment until now

**Comment by Bin-Huang** [comment]
Great job! I found a few minor bugs that could cause compatibility issues for users upgrading from older versions. I will fix them shortly.

**Comment by joegoldin** [comment]
Thanks! Appreciate all your work on this app! Looking forward to the Tauri rewrite 😄

**Pull request merged**
